# -*- coding: utf-8 -*-
__title__   = "Door Swing Detective"
__doc__     = """v1.0 | 17.02.2026 | JTH

DESCRIPTION:
- Exercise 2 of EF 21-Day Pyrevit Challenge
- Find mirrored door families

HOW-TO:
1. 

TODO:
[FEATURE] - 

Last Updates:
- [17.02.2026] Started the process!
"""


# IMPORTS ------------------------------------------------------

from Autodesk.Revit.DB import *

#.NET Imports
import clr
clr.AddReference('System')
from System.Collections.Generic import List

from Autodesk.Revit.UI.Selection import ObjectType


# VARIABLES ----------------------------------------------------

app    = __revit__.Application
uidoc  = __revit__.ActiveUIDocument
doc    = __revit__.ActiveUIDocument.Document #type:Document

# FUNCTIONS ----------------------------------------------------



# MAIN ---------------------------------------------------------

# 1. Get All Doors
cat = BuiltInCategory.OST_Doors
all_doors = FilteredElementCollector(doc).OfCategory().WhereElementIsNotElementType().ToElements()


# 2. Find Swing Direction
t = Transaction(doc, 'Door Swing')
t.Start() # ALLOWS CHANGES

for door in all_doors:
    val = 'Mirrored' if door.Mirrored else 'Unmirrored'
    print("Door is Mirrored: " + str(door.Mirrored))

    param = door.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS)
    param.Set(val)

t.Commit()
